using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SunMove : MonoBehaviour
{
    private const float secondsInRound = 300f; // 1ü‚·‚é‚Ì‚É‚©‚©‚é•b” (5•ª = 300•b)
    [SerializeField] private ClockController clock;
    void Start()
    {
        // ‘¾—z‚Ì‰Šú‚Ì‰ñ“]‚ğİ’è
        float initialRotation = (Time.time % secondsInRound) / secondsInRound * 360f;
        transform.eulerAngles = new Vector3(initialRotation, 0, 0);
    }

    void Update()
    {
        // ClockController‚©‚ç•bj‚ÌŠp“x‚Æ•b”‚ğæ“¾
        float secondHandAngle = ClockController.GetSecondHandAngle(Time.time);
        float seconds = ClockController.GetSeconds(Time.time);

        // ‘¾—z‚ÌˆÚ“®
        MoveSun(secondHandAngle, seconds);
    }

    void MoveSun(float secondHandAngle, float seconds)
    {
        // ƒQ[ƒ€“àŠÔ‚É‘Î‰‚·‚é‘¾—z‚Ì‰ñ“]‘¬“x‚ğŒvZ
        float sunRotationSpeed = 360f / secondsInRound;

        // •bj‚Ìü‰ñ”‚ğŒvZ
        float rotations = seconds / secondsInRound;

        // ‘¾—z‚Ìü‰ñ‚ÆŒv‚Ì‰ñ“]‚ğ‡‚í‚¹‚ÄˆÚ“®
        transform.rotation = Quaternion.Euler(secondHandAngle, 0, 0);
        transform.RotateAround(Vector3.zero, Vector3.up, 6f * rotations * 360f * Time.deltaTime); // 6f‚ÍŒv‚Ì•bj‚Ìü‰ñ‘¬“x
    }
}
